// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPY4jADi9zZQvwtm607GoszxbO2yUmiSU',
    appId: '1:655660888390:web:400043e924549b4eaa3547',
    messagingSenderId: '655660888390',
    projectId: 'official-x-twitter',
    authDomain: 'official-x-twitter.firebaseapp.com',
    storageBucket: 'official-x-twitter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrjGT0Od5uKO1bs-61sBkBCb1bVTSFM6Y',
    appId: '1:655660888390:android:2ac8a3fe5da04d68aa3547',
    messagingSenderId: '655660888390',
    projectId: 'official-x-twitter',
    storageBucket: 'official-x-twitter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD95hlCXisi0jAZmuHQI1pbKRJJjOXj6os',
    appId: '1:655660888390:ios:97dd72dfe4fe9098aa3547',
    messagingSenderId: '655660888390',
    projectId: 'official-x-twitter',
    storageBucket: 'official-x-twitter.appspot.com',
    iosClientId: '655660888390-rbh6v95pu1k2q64lk0onriikelb75vmf.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD95hlCXisi0jAZmuHQI1pbKRJJjOXj6os',
    appId: '1:655660888390:ios:946b19f0bf90c6e0aa3547',
    messagingSenderId: '655660888390',
    projectId: 'official-x-twitter',
    storageBucket: 'official-x-twitter.appspot.com',
    iosClientId: '655660888390-i5ajalmfs6sindvss72jmgja1laeam0o.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterclone.RunnerTests',
  );
}
